# -*- coding: utf-8 -*-

SECRET_KEY = "secRETsecRET"
SQLALCHEMY_DATABASE_URI = "mysql://root:123456@127.0.0.1:3306/llm_bench_sys"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SCHEDULER_API_ENABLED = True

OPENSEARCH_HOST = 'localhost'
OPENSEARCH_PORT = 9200
OPENSEARCH_USER = 'admin'
OPENSEARCH_PASSWORD = 'admin'
